{
  "openapi": "3.0.3",
  "info": {
    "title": "Kroger API Reference",
    "description": "# Introduction\nThe following APIs are publicly available to allow new clients to build products, \nservices, or customer experiences that leverage the unique data, functions, and \napplications of Kroger. As a company that strives to empower the developer community \nand meet our customers where they are, we are offering these APIs as the first \nstep to building an ecosystem that promotes speed, simplicity, and security.\n<br><br>\nAll Public APIs provide access to the foll[...]",
    "termsOfService": "https://developer.kroger.com/terms",
    "contact": {
      "name": "API Support",
      "email": "APISupport@kroger.com"
    },
    "version": "1.2.1"
  },
  "servers": [
    {
      "url": "https://api.kroger.com/v1",
      "description": "Production Environment"
    },
    {
      "url": "https://api-ce.kroger.com/v1",
      "description": "Certification Environment"
    }
  ],
  "security": [
    {
      "CustomerContext": [
        "profile.compact",
        "product.compact",
        "cart.basic:write"
      ]
    },
    {
      "ClientContext": [
        "product.compact"
      ]
    }
  ],
  "tags": [
    {
      "name": "Identity",
      "description": "The Identity API allows you to access the profile ID of an authenticated customer. <br><br>\n### Rate Limit\nThe Public Identity API has a **5,000 call per day** rate limit.\n"
    },
    {
      "name": "Products",
      "description": "The Products API allows you to search the Kroger product catalog. <br><br>\n\n### Rate Limit\n\nThe Public Products API has a **10,000 call per day** rate limit. \n\nFor all Public APIs, we enforce the rate limit by the number of calls the client makes to the endpoint, not individual API operations. This means you can distribute the 10,000 calls across all API operations using the `/products` endpoint as you see fit. <br><br>\n\n### Pagination\n\nThe Product Search operatio[...]"
    },
    {
      "name": "Locations",
      "description": "The Locations API provides access to all locations, chains, and departments that are owned by The Kroger Co. <br><br>\n\n### Rate Limit\n\nThe Public Locations API has a **1,600 call a day per endpoint** rate limit. \n\nFor the Locations API, there are three endpoints that each have a 1,600 call per day rate limit. Since we enforce the rate limit by the number of calls the client makes to the endpoint and not individual operations, you can distribute the 1,600 calls across [...]"
    },
    {
      "name": "Cart",
      "description": "The Cart API allows you to add an item to an authenticated customer's cart. <br><br>\n\n### Rate Limit\n\nThe Public Cart API has a **5,000 call per day** rate limit. \n"
    },
    {
      "name": "OAuth2",
      "description": "## Client Credentials Grant\nWhen using the Client Credentials grant type, you can use your application's \nclient credentials as a form of authentication. If you are making a request to an API \nthat requires an OAuth2 scope, the scope must be included in the token request. <br><br>\n\n## Authorization Code Grant\nTo authenticate a customer and act on their behalf, your application \nmust be able to perform both of the following steps of the Authorization Code grant. <br><[...]"
    }
  ],
  "paths": {
    "/connect/oauth2/authorize": {
      "get": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Authorization Code",
        "description": "The redirect URL to authenticate a customer and receive an authorization code.",
        "operationId": "authorizationCode",
        "security": [
          {
            "CustomerContext": [
              "profile.compact",
              "product.compact",
              "cart.basic:write"
            ]
          }
        ]
      }
    },
    "/connect/oauth2/token": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Access Token",
        "description": "The OAuth2 endpoint that provides access tokens.\n",
        "operationId": "accessToken",
        "security": [
          {
            "CustomerContext": [
              "profile.compact",
              "product.compact",
              "cart.basic:write"
            ]
          },
          {
            "ClientContext": [
              "product.compact"
            ]
          }
        ]
      }
    },
    "/identity/profile": {
      "get": {
        "tags": [
          "Identity"
        ],
        "summary": "User profile information",
        "description": "Provides access to the profile `id` of an authenticated customer. <br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization Code grant type.",
        "operationId": "profileGet",
        "security": [
          {
            "CustomerContext": [
              "profile.compact"
            ]
          }
        ]
      }
    },
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Product search",
        "description": "Allows you to find products by passing in either a search term or product Id.\n\n### Initial Search Value Required\n\nAn initial search value is requred for all requests. You can use either of the following parameters as an initial search value: \n\n`filter.term` - When using the term parameter, the API performs a fuzzy search based on the term provided in the string. Search results are based on how relevant the term is to the product description.\n\n`filter.productId` - [...]",
        "operationId": "productGet",
        "security": [
          {
            "CustomerContext": [
              "product.compact"
            ]
          },
          {
            "ClientContext": [
              "product.compact"
            ]
          }
        ]
      }
    },
    "/products/{id}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Product details",
        "description": "Provides access to the details of a specific product by either using the `productId` or `UPC`.",
        "operationId": "productGetID",
        "security": [
          {
            "CustomerContext": [
              "product.compact"
            ]
          },
          {
            "ClientContext": [
              "product.compact"
            ]
          }
        ]
      }
    },
    "/cart/add": {
      "put": {
        "tags": [
          "Cart"
        ],
        "summary": "Add to cart",
        "description": "Provides access to add items to an authenticated customer's cart. \n<br><br> **Note**: the customer must be authenticated using the\nOAuth2 Authorization Code grant type.\n",
        "operationId": "putCarts",
        "security": [
          {
            "CustomerContext": [
              "cart.basic:write"
            ]
          }
        ]
      }
    },
    "/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Location list",
        "description": "Provides access to a list of locations matching a given criteria. If the parameter `filter.chain` is not provided, the results include all locations and chains owned by The Kroger Co.<br> <h3>Starting Point Required</h3> You must include one of the following parameters as a starting point to narrow search results:<br><br> <ul> <li> <code>filter.zipCode.near</code></li> <li> <code>filter.latLong.near</code></li> <li> <code>filter.lat.near</code> and <code>filter.lon.near</[...]",
        "operationId": "SearchLocations",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Location details",
        "description": "Provides access to the details of a specific location by using the `locationId`.",
        "operationId": "LocationsGetByID",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Locations"
        ],
        "summary": "Location query",
        "description": "Determines if a specific location exists by using the `locationId`.",
        "operationId": "LocationsExistsByID",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/chains": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Chain list",
        "description": "Provides access to a list of all chains owned by The Kroger Co.",
        "operationId": "ListChains",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/chains/{name}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Chain details",
        "description": "Provides access to the details of a specific chian by using the chain `name`.",
        "operationId": "GetChain",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Locations"
        ],
        "summary": "Chain query",
        "description": "Determine if a specific chain exists by using the chain `name`.",
        "operationId": "ChainExists",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/departments": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Department list",
        "description": "Provides access to a list of all departments, including departments of chains owned by The Kroger Co.",
        "operationId": "ListDepartments",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/departments/{id}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Department details",
        "description": "Provides access to the details of a specific department by using the `departmentId`. ",
        "operationId": "GetDepartment",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Locations"
        ],
        "summary": "Department query",
        "description": "Determine if a specific department exists by using the `departmentId`. ",
        "operationId": "DepartmentExists",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ClientContext": {
        "type": "oauth2",
        "description": "When making API requests that do not require customer consent, you can use \nthe [Client Credentials Grant Type](#client-credentials-grant) to authenticate your OAuth2 \napplication.\n",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.kroger.com/v1/connect/oauth2/token",
            "scopes": {
              "product.compact": "Grants read access to general product information.",
              "N/A": "No scope required."
            }
          }
        }
      },
      "CustomerContext": {
        "type": "oauth2",
        "description": "When making an API request that is either returning personalized customer \ndata or acting on behalf of a customer, the customer's consent \nis required using the [Authorization Code Grant Type](#authorization-code-grant).\n",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.kroger.com/v1/connect/oauth2/authorize",
            "tokenUrl": "https://api.kroger.com/v1/connect/oauth2/token",
            "scopes": {
              "profile.compact": "Grants read access to a customer profile ID.",
              "cart.basic:write": "Grants write access to a customer's cart.",
              "product.compact": "Grants read access to general product information.",
              "N/A": "No scope required."
            }
          }
        }
      }
    }
  },
  "x-tagGroups": [
    {
      "name": "Authorization Endpoints",
      "tags": [
        "OAuth2"
      ]
    },
    {
      "name": "API Reference",
      "tags": [
        "Identity",
        "Cart",
        "Products",
        "Locations"
      ]
    }
  ]
}