// Holds variables, constants
// THESE ARE OUR ACTION TYPES FOLDER

export const SET_ITEM_TEST = 'SET_ITEM_TEST';
export const SET_ITEM_REQUEST = 'SET_ITEM_REQUEST';
export const SET_ITEM_SUCCESS = 'SET_ITEM_SUCCESS';
export const SET_ITEM_FAIL = 'SET_ITEM_FAIL';

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';
export const ITEM_DETAILS_FAIL = 'ITEM_DETAILS_FAIL';
